from setuptools import find_packages, setup

setup(
    name="flex",
    version="0.0.1.dev0",
    author="The FLEXible team",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    keywords="FL federated-learning flexible",
    url="https://github.com/FLEXible-FL/FLEX-framework",
    packages=find_packages(),
    install_requires=["numpy",
                    "multiprocess",
                    "scikit-learn",
                    "cardinality",
                    "lazyarray",
                    "sultan",
                    "tqdm",
                    "scipy",
                    "gdown"
                    ],
    extras_require={
        "tensorflow": ["tensorflow<2.11", 
                "tensorflow_datasets", 
                "tensorflow_hub"
                ],
        "pytorch": ["torch", 
                "torchvision", 
                "torchtext", 
                "torchdata",
                "portalocker",
                ],
        "hugginface": ["datasets"],
        "develop": ["pytest",
                "pytest-cov",
                "pytest-xdist",
                "coverage",
                "jinja2",
                "tensorflow<2.11",
                "tensorflow_datasets",
                "tensorflow_hub",
                "torch",
                "torchvision",
                "torchtext",
                "torchdata",
                "datasets"
                ],
    },
    python_requires=">=3.9.0",
)
