# This workflow will install dependencies, create coverage tests and run Pytest Coverage Comment
# For more information see: https://github.com/MishaKav/pytest-coverage-comment/
name: Tests
on:
  pull_request:
    branches:
      - main
    types: [synchronize, opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python 3.10.16
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.16

      - name: Install dependencies
        run: |
          uv pip install flake8 pytest pytest-cov
          uv pip install ".[develop]"
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Build coverage file
        run: |
          pytest -n 2 --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=flex tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          report-only-changed-files: false
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
